### ISSUE TITLE
can't sync

### ISSUE THREAD

**Issue by unique83** [Team-Hycon/hycon-core#3]
Can't sync on windows. I keep getting these messages

```
[2018-06-05 19:53:46.763] [INFO] CpuMiner - CPU Hashrate: 0 H/s / CPU Count : 1
[2018-06-05 19:53:48.074] [INFO] Sync - No peer to sync with, Local=0
```

Is there a reason for this?
How can i fix this?

**Comment by kenold** [comment]
I'm having the same issue on Windows 10, 64Bit Machine. 
![image](https://user-images.githubusercontent.com/6126841/41008049-cf89d03c-68f6-11e8-9263-146d1e928a80.JPG)

**Comment by jmelett** [comment]
Same here, my guess is that it's related to UPnP (which is enabled on my router):

```
[2018-06-06 15:09:34.129] [DEBUG] Nat - Failed to map port 8148 --> 8148, Attempt 0 of 5
[2018-06-06 15:09:35.931] [DEBUG] Nat - Failed to map port 8148 --> 51062, Attempt 1 of 5
[2018-06-06 15:09:37.732] [DEBUG] Nat - Failed to map port 8148 --> 56456, Attempt 2 of 5
[2018-06-06 15:09:37.983] [INFO] RestClient - other: /api/v1/blockList/0
[2018-06-06 15:09:39.536] [DEBUG] Nat - Failed to map port 8148 --> 58700, Attempt 3 of 5
[2018-06-06 15:09:41.341] [DEBUG] Nat - Failed to map port 8148 --> 53393, Attempt 4 of 5
[2018-06-06 15:09:41.341] [DEBUG] Nat - Upnp Port mapping failed
[2018-06-06 15:09:41.342] [DEBUG] Nat - Upnp Warning: Error: Upnp Port mapping failed, please confirm your router supports UPNP and that UPNP is enabled or you just not behind the NAT, Hycon will use your local port:8148
[2018-06-06 15:09:42.133] [INFO] CpuMiner - CPU Hashrate: 0 H/s
[2018-06-06 15:09:43.144] [DEBUG] Nat - Get external IP failed, hycon will use your local IP: if you are not behind NAT
```


Tested on OS X 10.13.2 (`Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`)

**Comment by unique83** [comment]
I have upnp enabled and I don't get this upnp error

**Comment by dumprat** [comment]
I had sync issue also in win10 + mac...

To resolve:
1) go to http://hplorer.com/peers
2) open a shell and try to ping the hosts on the peer list ("ping xxx.xxx.xx.xx") until you find one that does not time out:

**_MacBook-Pro:~ dump_rat$** ping 116.122.128.49
PING 116.122.128.49 (116.122.128.49): 56 data bytes
64 bytes from 116.122.128.49: icmp_seq=0 ttl=40 time=249.023 ms
64 bytes from 116.122.128.49: icmp_seq=1 ttl=40 time=224.698 ms
64 bytes from 116.122.128.49: icmp_seq=2 ttl=40 time=255.991 ms_
^Z

3) open your launch script and add parameter to force peer (use the value in the "connection string" column for the valid host you previously pinged).
_./hycon --api --api_port=2442 **--peer 116.122.128.49:63975** --cpuMiners=1 $@_

**Comment by icemanphd** [comment]
Sync issues should be fixed in the latest release .5 release

**Comment by BrahmaGithub** [comment]
Sync issue is still around.
0.0.5c Windows 7
http://hplorer.com/peers -> No rows found

> [2018-06-24 02:27:58.763] [INFO] CpuMiner - CPU Hashrate: 0 H/s / CPU Count : 1
> [2018-06-24 02:28:00.023] [INFO] Network - Peers Count=0  PeerDB Size= 0
> [2018-06-24 02:28:00.028] [INFO] Sync - No peer to sync with, Local=0
